

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
    command: npx next dev --webpack


  db:
    image: postgres:18
    env_file:
      - .env.docker
    ports:
    - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./seed:/docker-entrypoint-initdb.d

volumes:
  db_data:
