services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - mongo

  db:
    image: postgres:18
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: questmaker
        DATABASE_URL: postgresql://docker:docker@db:5432/questmaker
    ports:
    - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/001_dump.sql:ro

  mongo:
    image: mongo:7
    env_file:
      - .env.docker

volumes:
  db_data:
