export const merchantGreetings: string[] = [
  "Welcome, traveler. Care to browse my wares?",
  "Looking for supplies? I’ve got what you need.",
  "Take your time. A wise buyer is a living buyer.",
  "Step closer and have a look.",
  "See anything you like?",
  "Best goods in town, if I do say so myself.",
  "Need something for the road?",
  "Coin first, questions later. Just kidding. Mostly.",
  "Have a look around.",
  "If you’ve got coin, I’ve got goods.",

  "Ah, a customer. Fortune smiles upon us both.",
  "Fresh stock from distant lands. Rare finds, fair prices.",
  "Blades, potions, trinkets—everything an adventurer needs.",
  "The road is cruel. My wares may keep you alive.",
  "A good weapon can mean the difference between glory and a grave.",
  "Welcome to my humble shop. May you find what fate withheld.",
  "Care to trade? I deal in quality, not scraps.",
  "Choose well. Out there, mistakes are expensive.",
  "I’ve items blessed by luck… or cursed by rumor.",
  "Browse freely, but mind your hands.",

  "Hey there, friend. What can I get for you today?",
  "Good to see a new face. Come take a look.",
  "You look like you’ve been through a lot. Restock while you can.",
  "No rush. I’ll be here.",
  "If you need gear, you came to the right place.",
  "Welcome in. Let’s see what suits you.",
  "Looking for something special?",
  "Come in, come in. Don’t be shy.",
  "Take a look—there might be just what you need.",
  "Glad you stopped by.",

  "Ah! I can already tell you have excellent taste.",
  "For you? A special price. Truly.",
  "Don’t let the prices scare you—the quality is worth it.",
  "Rare goods, limited stock, and no refunds.",
  "Buy now, thank me later.",
  "I sell solutions, not just items.",
  "Everything has a price, and mine are reasonable.",
  "If you can carry it, I can sell it.",
  "You won’t find better deals… unless you do.",
  "Coin talks. Let’s listen.",

  "If you’re heading out there, you’ll need more than courage.",
  "Buy what you need. The wilds show no mercy.",
  "Supplies are scarce. Don’t waste my time.",
  "The dead don’t spend coin. Choose wisely.",
  "Every item here has a story. Most end badly.",
  "Take what you need and move along.",
  "I trade in survival.",
  "You look like trouble. Good. Trouble pays.",
  "Make it quick. Danger doesn’t wait.",

  "Welcome! Please ignore the smell, it adds character.",
  "Looking for something sharp, shiny, or suspiciously magical?",
  "If it explodes, glows, or leaks, it’s on the back shelf.",
  "I sell only the finest questionable decisions.",
  "Potions, blades, snacks—adventuring essentials.",
  "Don’t touch that one. Actually… do you have gold?",
  "Everything’s legal. Probably.",
  "Come browse my absolutely honest merchandise.",
  "If you break it, you buy it. If it bites you, also you buy it.",
  "Ah, a customer! My favorite kind of interruption.",

  "Need potions? I have brews for every kind of disaster.",
  "Healing, mana, antidotes—what’s your poison?",
  "Freshly brewed and carefully bottled.",
  "A vial a day keeps the grave away.",
  "Potions for wounds, fatigue, and poor decisions.",
  "If you can drink it, I probably sell it.",
  "Looking for remedies or something stronger?",
  "My mixtures are potent—use them wisely.",
  "Stock up before your next fight.",
  "One sip can change your fate.",

  "Need steel? I’ve got blades that bite hard.",
  "Looking for a weapon worthy of your hand?",
  "Fine steel, forged to last.",
  "Armor, blades, and tools—pick your edge.",
  "A dull blade kills slower. I can fix that.",
  "If it’s made of iron, I can sell it.",
  "You fight, I forge. Fair trade.",
  "Gear up before you regret it.",
  "Strong steel for hard roads.",
  "Let’s see what fits your style.",

  "Browse my wares.",
  "Need supplies?",
  "Care to trade?",
  "Take a look.",
  "Spend wisely.",
  "Looking to buy?",
  "Welcome, traveler.",
  "Got coin?",
  "Trade?",
  "See anything?",

  "The road leaves marks. My wares help you leave fewer.",
  "Gold is easier to earn than a second chance—equip yourself well.",
  "I’ve seen heroes die for lack of a single potion.",
  "Every journey begins with hope. Most continue with supplies.",
  "Fate favors the prepared. Browse, and prepare.",
  "Out there, skill matters. So does good equipment."
];